In [1]:
numbers=[10,20,30,40,50]
print(numbers)

[10, 20, 30, 40, 50]


In [16]:
#Create this NumPy array:
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers)
#type
print(type(numbers))
#four properties:shape, ndim,size,dtype
# 1.ndim--Number Of Dimensions
print(numbers.ndim)
#2.shape — Structure of the Array
#shape=(x,) for 1D array which means x elemnet along its only dimension.
#shape = (rows, columns) for a 2D array.
print(numbers.shape)
#3.size — Total Number of Elements
print(numbers.size)
#4.dtype — Data Type
print(numbers.dtype)
#Multiply every element by 2
num=np.array([5,10,15,20])
doubled_numbers=num*2
print(doubled_numbers)


[10 20 30 40 50]
<class 'numpy.ndarray'>
1
(5,)
5
int32
[10 20 30 40]


#Question:
Why is numbers * 2 possible with a NumPy array, while doing the same thing with a normal Python list doesn't multiply each element?
-------------------------------------
"NumPy supports vectorized operations, which allow us to perform operations on entire arrays without explicitly writing Python loops. With a normal Python list, element-wise numerical operations generally require an explicit loop or comprehension."
⭐ NumPy → vectorization → less explicit looping → efficient numerical computation


Lesson 3 — NumPy Indexing
-------------------------------------------------
Indexing means accessing a particular element from an array.
Python and NumPy use zero-based indexing.
That means counting starts from 0, not 1.

In [21]:

import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers[3])
print(numbers[-2])

40
40


Negative indexing
---------------------
You can also count from the end:
Value:     10   20   30   40   50
Index:      0    1    2    3    4
Negative:  -5   -4   -3   -2   -1

In [26]:
import numpy as np
marks = np.array([
    [80, 90, 70],
    [75, 85, 95],
    [88, 92, 84]
])
# to access an elemnt 
#marks[row,column]
print(marks[0,1])
print(marks[:,0]) #first column(All rows, column 0)
print(marks[:,2]) #third column
print(marks[:,-1] )#third column
print(marks[2])    #last row
print(marks[:, :]) # all rows , columns

90
[80 75 88]
[70 95 84]
[70 95 84]
[88 92 84]
[[80 90 70]
 [75 85 95]
 [88 92 84]]


Lesson 4 — NumPy Slicing
---------------------------------------------
Slicing means taking a portion of an array.
The basic syntax is:
array[start:stop]
⚠️ The stop index is not included.

In [33]:
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers[1:4])#Start at index 1, stop before index 4.
print(numbers[0:3])#Start at index 0, stop before index 3.
print(numbers[:3]) #start from beginning
print(numbers[2:]) #continue until the end
print(numbers[:])# entire array

[20 30 40]
[10 20 30]
[10 20 30]
[30 40 50]
[10 20 30 40 50]


2D Slicing
-----------------------------------------
marks[row_start:row_stop, column_start:column_stop]

In [34]:
import numpy as np
marks = np.array([
    [80, 90, 70, 60],
    [75, 85, 95, 65],
    [88, 92, 84, 72]
])
print(marks[0:2,1:3])

[[90 70]
 [85 95]]


STEP:
---------------------------------
Use the step value to determine the step of the slicing:

In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


Lesson 5 — Modifying NumPy Arrays ✏️
---------------------------------

In [46]:
import numpy as np
mark = np.array([80, 90, 70, 60])
mark[1] = 75
mark[2:]=0
mark[1:4] = [100, 200, 300]
print(mark)
marks = np.array([
    [80, 90, 70],
    [75, 85, 95],
    [88, 92, 84]
])
#marks[1,2]=101
marks[0,2]=100

marks[2,2]=90

marks[1]=100

marks[:,1:]=0
print(marks)


[ 80 100 200 300]
[[ 80   0   0]
 [100   0   0]
 [ 88   0   0]]


Lesson 6 — NumPy Array Creation Methods 
-----------------------------------------------

In [63]:
import numpy as np
arr=np.zeros(5)
arrr=np.zeros((2,3))
array=np.ones(5)
ab=np.arange(5)
bc=np.arange(2,10)
cd=np.arange(2,10,2)
de=np.random.rand(5)
ed=np.random.randint(5)
ef=np.random.randint(1,10,5)
print("Creates an array where every value is 0.")
print("---1D array---")
print(arr)
print("---2D array---")
print(arrr)
print("Creates an array filled with 1.")
print(array)
print("np.arange():It creates numbers within a range.")
print(ab)
print("---Start and stop----")
print(bc)
print("---With step---------")
print(cd)
print("np.random:-NumPy can also generate random numbers.")
print(de)
print(ed)
print("Generate 5 random integers from 1 up to 10 (10 excluded)")
print(ef)



Creates an array where every value is 0.
---1D array---
[0. 0. 0. 0. 0.]
---2D array---
[[0. 0. 0.]
 [0. 0. 0.]]
Creates an array filled with 1.
[1. 1. 1. 1. 1.]
np.arange():It creates numbers within a range.
[0 1 2 3 4]
---Start and stop----
[2 3 4 5 6 7 8 9]
---With step---------
[2 4 6 8]
np.random:-NumPy can also generate random numbers.
[0.27420573 0.20839738 0.9348318  0.00787985 0.46098137]
1
Generate 5 random integers from 1 up to 10 (10 excluded)
[1 9 6 9 8]


🧠 Very important comparison
------------------------------

Lesson 7 — NumPy dtype
----------------------
What is dtype?-->
dtype means data type.
Every NumPy array has a dtype that tells us what type of values it stores.

Common NumPy data types
---------------------------

Lesson 8 — NumPy Mathematical Operations
----------------------------------------

In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print("NumPy adds 5 to every element:ADDITION")
print(arr+5)
print("NumPy subract 5 to every element:Subraction")
print(arr-5)
print("Multiplication")
print(arr*5)
print("DIVISION")
print(arr/5)

NumPy adds 5 to every element:ADDITION
[15 25 35 45]
NumPy subract 5 to every element:Subraction
[ 5 15 25 35]
Multiplication
[ 50 100 150 200]
DIVISION
[2. 4. 6. 8.]


Array+Array
------------

In [7]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


Vectorization 
-------------
Vectorization is the process of performing operations on entire NumPy arrays without explicitly writing Python loops, making numerical computations concise and generally more efficient.

Mathematical functions:
-------------------------
Square root , Power , Absolute value

In [14]:
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))
print("This squares every element.")
print(np.power(arr, 2))
ar = np.array([-10, 5, -3])
print(np.abs(ar))

[1. 2. 3. 4.]
This squares every element.
[  1  16  81 256]
[10  5  3]


Lesson 9 — NumPy Aggregation Functions
--------------------------------------
Aggregation functions summarize an entire dataset into a single value.

In [24]:
import numpy as np
marks = np.array([80, 90, 70, 60, 100])
sum=np.sum(marks)
print("Sum:",sum)
mean=np.mean(marks)
print("Mean:",mean)
median=np.median(marks)
print("Median:",median)
max=np.max(marks)
print("Max",max)
min=np.min(marks)
print("MIN",min)
print(np.std(marks))
print(np.var(marks))

Sum: 400
Mean: 80.0
Median: 80.0
Max 100
MIN 60
14.142135623730951
200.0


Important Concept:axis
--------------------------

axis=0 → column-wise → result for each column


axis=1 → row-wise → result for each row

In [34]:
marks = np.array([
    [80, 90, 70],
    [75, 85, 95],
    [88, 92, 84]
])
Total_sum=np.sum(marks)
print("Total_sum:",Total_sum)
Max_value=np.max(marks)
print("Max_value:",Max_value)
Avg_SubjectWise=np.mean(marks,axis=0)
print("Avg_SubjectWise:",Avg_SubjectWise)
Total_marksStudentwise=np.sum(marks,axis=1)
print("Total_marksStudentwise:",Total_marksStudentwise)
print(np.min(marks,axis=0))

Total_sum: 759
Max_value: 95
Avg_SubjectWise: [81. 89. 83.]
Total_marksStudentwise: [240 255 264]
[75 85 70]


Lesson 10 — Comparison Operations & Boolean Indexing
----------------------------------------------------

array[condition] → returns only the elements where the condition is True.


In [45]:
marks = np.array([45, 67, 82, 91, 55])
marks > 80
marks[marks > 60]

array([67, 82, 91])

In [59]:
marks = np.array([45, 67, 82, 91, 55, 73, 88]) 
print(marks>70) 
print(marks[marks>70]) 
print(marks[marks<60])
print(marks[marks>=80]) 
print(marks[(marks >= 60) & (marks <= 80)])

[False False  True  True False  True  True]
[82 91 73 88]
[45 55]
[82 91 88]
[67 73]
