In [1]:
numbers=[10,20,30,40,50]
print(numbers)

[10, 20, 30, 40, 50]


In [16]:
#Create this NumPy array:
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers)
#type
print(type(numbers))
#four properties:shape, ndim,size,dtype
# 1.ndim--Number Of Dimensions
print(numbers.ndim)
#2.shape — Structure of the Array
#shape=(x,) for 1D array which means x elemnet along its only dimension.
#shape = (rows, columns) for a 2D array.
print(numbers.shape)
#3.size — Total Number of Elements
print(numbers.size)
#4.dtype — Data Type
print(numbers.dtype)
#Multiply every element by 2
num=np.array([5,10,15,20])
doubled_numbers=num*2
print(doubled_numbers)


[10 20 30 40 50]
<class 'numpy.ndarray'>
1
(5,)
5
int32
[10 20 30 40]


#Question:
--------
Why is numbers * 2 possible with a NumPy array, while doing the same thing with a normal Python list doesn't multiply each element?

"NumPy supports vectorized operations, which allow us to perform operations on entire arrays without explicitly writing Python loops. With a normal Python list, element-wise numerical operations generally require an explicit loop or comprehension."

⭐ NumPy → vectorization → less explicit looping → efficient numerical computation


Lesson 3 — NumPy Indexing
-------------------------------------------------
Indexing means accessing a particular element from an array.
Python and NumPy use zero-based indexing.
That means counting starts from 0, not 1.

In [21]:

import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers[3])
print(numbers[-2])

40
40


Negative indexing
---------------------
You can also count from the end:
Value:     10   20   30   40   50
Index:      0    1    2    3    4
Negative:  -5   -4   -3   -2   -1

In [26]:
import numpy as np
marks = np.array([
    [80, 90, 70],
    [75, 85, 95],
    [88, 92, 84]
])
# to access an elemnt 
#marks[row,column]
print(marks[0,1])
print(marks[:,0]) #first column(All rows, column 0)
print(marks[:,2]) #third column
print(marks[:,-1] )#third column
print(marks[2])    #last row
print(marks[:, :]) # all rows , columns

90
[80 75 88]
[70 95 84]
[70 95 84]
[88 92 84]
[[80 90 70]
 [75 85 95]
 [88 92 84]]


Lesson 4 — NumPy Slicing
---------------------------------------------
Slicing means taking a portion of an array.
The basic syntax is:
array[start:stop]
⚠️ The stop index is not included.

In [33]:
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers[1:4])#Start at index 1, stop before index 4.
print(numbers[0:3])#Start at index 0, stop before index 3.
print(numbers[:3]) #start from beginning
print(numbers[2:]) #continue until the end
print(numbers[:])# entire array

[20 30 40]
[10 20 30]
[10 20 30]
[30 40 50]
[10 20 30 40 50]


2D Slicing
-----------------------------------------
marks[row_start:row_stop, column_start:column_stop]

In [34]:
import numpy as np
marks = np.array([
    [80, 90, 70, 60],
    [75, 85, 95, 65],
    [88, 92, 84, 72]
])
print(marks[0:2,1:3])

[[90 70]
 [85 95]]


STEP:
---------------------------------
Use the step value to determine the step of the slicing:

In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


Lesson 5 — Modifying NumPy Arrays ✏️
---------------------------------

In [46]:
import numpy as np
mark = np.array([80, 90, 70, 60])
mark[1] = 75
mark[2:]=0
mark[1:4] = [100, 200, 300]
print(mark)
marks = np.array([
    [80, 90, 70],
    [75, 85, 95],
    [88, 92, 84]
])
#marks[1,2]=101
marks[0,2]=100

marks[2,2]=90

marks[1]=100

marks[:,1:]=0
print(marks)


[ 80 100 200 300]
[[ 80   0   0]
 [100   0   0]
 [ 88   0   0]]


Lesson 6 — NumPy Array Creation Methods 
-----------------------------------------------

In [63]:
import numpy as np
arr=np.zeros(5)
arrr=np.zeros((2,3))
array=np.ones(5)
ab=np.arange(5)
bc=np.arange(2,10)
cd=np.arange(2,10,2)
de=np.random.rand(5)
ed=np.random.randint(5)
ef=np.random.randint(1,10,5)
print("Creates an array where every value is 0.")
print("---1D array---")
print(arr)
print("---2D array---")
print(arrr)
print("Creates an array filled with 1.")
print(array)
print("np.arange():It creates numbers within a range.")
print(ab)
print("---Start and stop----")
print(bc)
print("---With step---------")
print(cd)
print("np.random:-NumPy can also generate random numbers.")
print(de)
print(ed)
print("Generate 5 random integers from 1 up to 10 (10 excluded)")
print(ef)



Creates an array where every value is 0.
---1D array---
[0. 0. 0. 0. 0.]
---2D array---
[[0. 0. 0.]
 [0. 0. 0.]]
Creates an array filled with 1.
[1. 1. 1. 1. 1.]
np.arange():It creates numbers within a range.
[0 1 2 3 4]
---Start and stop----
[2 3 4 5 6 7 8 9]
---With step---------
[2 4 6 8]
np.random:-NumPy can also generate random numbers.
[0.27420573 0.20839738 0.9348318  0.00787985 0.46098137]
1
Generate 5 random integers from 1 up to 10 (10 excluded)
[1 9 6 9 8]


🧠 Very important comparison
------------------------------

Lesson 7 — NumPy dtype
----------------------
What is dtype?-->
dtype means data type.
Every NumPy array has a dtype that tells us what type of values it stores.

Common NumPy data types
---------------------------

Lesson 8 — NumPy Mathematical Operations
----------------------------------------

In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print("NumPy adds 5 to every element:ADDITION")
print(arr+5)
print("NumPy subract 5 to every element:Subraction")
print(arr-5)
print("Multiplication")
print(arr*5)
print("DIVISION")
print(arr/5)

NumPy adds 5 to every element:ADDITION
[15 25 35 45]
NumPy subract 5 to every element:Subraction
[ 5 15 25 35]
Multiplication
[ 50 100 150 200]
DIVISION
[2. 4. 6. 8.]


Array+Array
------------

In [7]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


Vectorization 
-------------
Vectorization is the process of performing operations on entire NumPy arrays without explicitly writing Python loops, making numerical computations concise and generally more efficient.

Mathematical functions:
-------------------------
Square root , Power , Absolute value

In [14]:
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))
print("This squares every element.")
print(np.power(arr, 2))
ar = np.array([-10, 5, -3])
print(np.abs(ar))

[1. 2. 3. 4.]
This squares every element.
[  1  16  81 256]
[10  5  3]


Lesson 9 — NumPy Aggregation Functions
--------------------------------------
Aggregation functions summarize an entire dataset into a single value.

In [24]:
import numpy as np
marks = np.array([80, 90, 70, 60, 100])
sum=np.sum(marks)
print("Sum:",sum)
mean=np.mean(marks)
print("Mean:",mean)
median=np.median(marks)
print("Median:",median)
max=np.max(marks)
print("Max",max)
min=np.min(marks)
print("MIN",min)
print(np.std(marks))
print(np.var(marks))

Sum: 400
Mean: 80.0
Median: 80.0
Max 100
MIN 60
14.142135623730951
200.0


Important Concept:axis
--------------------------

axis=0 → column-wise → result for each column


axis=1 → row-wise → result for each row

In [60]:
marks = np.array([
    [80, 90, 70],
    [75, 85, 95],
    [88, 92, 84]
])
Total_sum=np.sum(marks)
print("Total_sum:",Total_sum)
Max_value=np.max(marks)
print("Max_value:",Max_value)
Avg_SubjectWise=np.mean(marks,axis=0)
print("Avg_SubjectWise:",Avg_SubjectWise)
Total_marksStudentwise=np.sum(marks,axis=1)
print("Total_marksStudentwise:",Total_marksStudentwise)
print(np.min(marks,axis=0))

Total_sum: 759
Max_value: 95
Avg_SubjectWise: [81. 89. 83.]
Total_marksStudentwise: [240 255 264]
[75 85 70]


Lesson 10 — Comparison Operations & Boolean Indexing
----------------------------------------------------

array[condition] → returns only the elements where the condition is True.


In [45]:
marks = np.array([45, 67, 82, 91, 55])
marks > 80
marks[marks > 60]

array([67, 82, 91])

In [59]:
marks = np.array([45, 67, 82, 91, 55, 73, 88]) 
print(marks>70) 
print(marks[marks>70]) 
print(marks[marks<60])
print(marks[marks>=80]) 
print(marks[(marks >= 60) & (marks <= 80)])

[False False  True  True False  True  True]
[82 91 73 88]
[45 55]
[82 91 88]
[67 73]


Lesson 11 — Boolean Indexing with 2D Arrays
-------------------------------------------

In [66]:
import numpy as np
marks = np.array([
    [80, 90, 70],
    [75, 85, 95],
    [88, 92, 84]
]) 
print(marks[marks > 85]) 
print(marks[(marks >= 80) & (marks <= 90)])
ages = np.array([18, 22, 15, 30, 17, 25])
print(ages[ages >= 18])

[90 95 88 92]
[80 90 85 88 84]
[18 22 30 25]


2D array → Boolean filtering → selected 
--------------------------------------

In [80]:
marks=np.array([
    [45,78,92],
    [66,55,88],
    [91,73,60],
    [82,95,49]
]) 
print("Get all marks greater than 80")
print(marks[marks>80]) 
print("Get all marks less than 60")
print(marks[marks<60]) 
print("Get all marks between 60 and 80, inclusive.") 
print(marks[(marks>=60)&(marks<=80)]) 
print("Count how many marks are greater than 80.")
print(np.sum(marks>80)) 
marks[marks<50]=0
print(marks)

Get all marks greater than 80
[92 88 91 82 95]
Get all marks less than 60
[45 55 49]
Get all marks between 60 and 80, inclusive.
[78 66 73 60]
Count how many marks are greater than 80.
5
[[ 0 78 92]
 [66 55 88]
 [91 73 60]
 [82 95  0]]


Lesson 12: Fancy Indexing
--------------------------
Fancy indexing means selecting specific elements, rows, or columns using an array/list of indices.
arr[[index1, index2, ...]]

In [87]:
arr = np.array([10, 20, 30, 40, 50])
arr[[1, 3]] 


array([20, 40])

In [92]:
marks = np.array([
    [45, 78, 92],
    [66, 55, 88],
    [91, 73, 60],
    [82, 95, 49]
])
print("Select row 1 and row 3:",marks[[1, 3]]) 
print("To select columns 0 and 2:",marks[:, [0, 2]])
print("Select rows 0 and 2:",marks[[0,2]]) 
print("Select rows 1 and 3:",marks[[1,3]])
print("select columns 0 and 2:",marks[:,[0,2]])
print("select columns 1 and 2:",marks[:,[1,2]])
print("Select rows 0 and 3, but only columns 1 and 2:",marks[[0, 3]][:, [1, 2]])

Select row 1 and row 3: [[66 55 88]
 [82 95 49]]
To select columns 0 and 2: [[45 92]
 [66 88]
 [91 60]
 [82 49]]
Select rows 0 and 2: [[45 78 92]
 [91 73 60]]
Select rows 1 and 3: [[66 55 88]
 [82 95 49]]
select columns 0 and 2: [[45 92]
 [66 88]
 [91 60]
 [82 49]]
select columns 1 and 2: [[78 92]
 [55 88]
 [73 60]
 [95 49]]
Select rows 0 and 3, but only columns 1 and 2: [[78 92]
 [95 49]]


🧠 Fancy Indexing vs Boolean Indexing
--------------------------------------

marks[[0, 2]]	Select specific indices
marks[marks > 80]	Select based on condition
Think:
Fancy indexing → "Give me these positions."
Boolean indexing → "Give me everything satisfying this condition."

Lesson 13 — reshape() & Shape Manipulation
---------------------------------------------
reshape():changes the shape of an array without changing its data.

In [95]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr.shape
arr.size
arr.reshape(3, 4) 
arr.reshape(4,3)
arr.reshape(2, 1, 3)
arr.reshape(2,-1)
arr.reshape(-1,3)


array([[[1, 2, 3]],

       [[4, 5, 6]]])

Lesson 14 — flatten() vs ravel()
---------------------------------
Both are used to convert a multidimensional array into 1D
<--flatten() always returns a copy of the array, while ravel() returns a flattened view when possible, making ravel() generally more memory-efficient."-->

In [105]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr.shape
flat = arr.flatten()
print(flat)
flat[0]=100
print("The original generally remains:flatten()made a copy")
print(arr)
flats = arr.ravel()
print(flats)
flats[0] = 100
print("You may see:because the raveled result can share memory with arr")
print(arr)

[1 2 3 4 5 6]
The original generally remains:flatten()made a copy
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
You may see:because the raveled result can share memory with arr
[[100   2   3]
 [  4   5   6]]


In [112]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print("Use flatten() and print the result")
flat=arr.flatten()
print(flat)
print(flat.shape)
flat[0]=999
print(arr)
print("Use ravel() and print the result")
flats=arr.ravel()
print(flats)
print(flats.shape)
flats[0]=999
print(arr)

Use flatten() and print the result
[10 20 30 40 50 60]
(6,)
[[10 20 30]
 [40 50 60]]
Use ravel() and print the result
[10 20 30 40 50 60]
(6,)
[[999  20  30]
 [ 40  50  60]]


Lesson 15 — Transpose .T and np.transpose()
------------------------------------------
Transpose is used to swap rows and columns.

In [118]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])
print("Before Transpose shape Of Array:",arr.shape)
new_arr=arr.T
print(new_arr)
print("After Transpose shape Of Array:",new_arr.shape)
arr.T == np.transpose(arr)

Before Transpose shape Of Array: (2, 3)
[[1 4]
 [2 5]
 [3 6]]
After Transpose shape Of Array: (3, 2)


array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [121]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Print the original shape:",arr.shape)
new_arr=arr.T
print("Transpose the array using .T:",new_arr)
print("Print the shape after transpose:",new_arr.shape)
Second_arr=np.transpose(arr)
print("Transpose the same array using np.transpose():",Second_arr)
print("Check whether .T and np.transpose() produce the same result:",new_arr==Second_arr)

Print the original shape: (3, 3)
Transpose the array using .T: [[10 40 70]
 [20 50 80]
 [30 60 90]]
Print the shape after transpose: (3, 3)
Transpose the same array using np.transpose(): [[10 40 70]
 [20 50 80]
 [30 60 90]]
Check whether .T and np.transpose() produce the same result: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Instead of:
-----------------------
arr.T == np.transpose(arr)
<--------you can use:-------->
np.array_equal(arr.T, np.transpose(arr))

Lesson 16 — Combining NumPy Arrays
----------------------------------
concatenate(), vstack(), and hstack().

1️⃣ np.concatenate()
-------------------
concatenate(): means join arrays together.
Start with two 1D arrays:

In [1]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

result=np.concatenate((a,b))
print(result)

[1 2 3 4 5 6]


2️⃣ concatenate() with 2D arrays
----------------------------
    axis=0 → Vertical(The rows increase.)
    axis=1 → Horizontal(The columns increase)

In [7]:
a=np.array([
    [1,2],
    [3,4]
])
b=np.array([
    [5,6],
    [7,8]
])
print("Shape Of anarray A:",a.shape)
rowise= np.concatenate((a,b),axis=0)
print("Combine them using axis=0/rowise:",rowise)
print("Shape Of an array B:",b.shape)
columnwise=np.concatenate((a,b),axis=1)
print("combine them using axis=1/columnwise:",columnwise)

Shape Of anarray A: (2, 2)
Combine them using axis=0/rowise: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape Of an array B: (2, 2)
combine them using axis=1/columnwise: [[1 2 5 6]
 [3 4 7 8]]


3️⃣np.vstack()
---------------
vstack = vertical stack️
<-----It's similar to:
np.concatenate((a, b), axis=0)------>

In [8]:
result=np.vstack((a,b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


4️⃣np.hstack()
---------------------------------
hstack = horizontal stack️
<----It's similar to:
np.concatenate((a, b), axis=1)--->

In [9]:
result=np.hstack((a,b))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


🎯 Example
-------------

In [10]:
hr=np.array([
    [101,25000],
    [102,30000]
])
sales=np.array([
    [103,28000],
    [104,35000]
])
employees=np.vstack((hr,sales))
print(employees)

[[  101 25000]
 [  102 30000]
 [  103 28000]
 [  104 35000]]


📝 Your Practice
-------------------


In [16]:
a=np.array([
    [10,20],
    [30,40]
])
b=np.array([
    [50,60],
    [70,80]
])
print("Combine a and b using with axis=0:")
rowise=np.concatenate((a,b),axis=0)
print(rowise)
print("combine a and b using with axis=1:")
columnwise=np.concatenate((a,b),axis=1)
print(columnwise)
print("Combine them using np.vstack():")
result=np.vstack((a,b))
print(result)
print("combine them using np.hstack():")
result=np.hstack((a,b))
print(result)
print("shapes of:np.concatenate((a, b), axis=0):",rowise.shape)
print("shapes of:np.concatenate((a, b), axis=1):",columnwise.shape)


Combine a and b using with axis=0:
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
combine a and b using with axis=1:
[[10 20 50 60]
 [30 40 70 80]]
Combine them using np.vstack():
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
combine them using np.hstack():
[[10 20 50 60]
 [30 40 70 80]]
shapes of:np.concatenate((a, b), axis=0): (4, 2)
shapes of:np.concatenate((a, b), axis=1): (2, 4)


🎯 Interview-ready answer
-------------------------------
<---np.concatenate() joins arrays along a specified axis.--->
<---vstack() stacks arrays vertically, while hstack() stacks them horizontally.---->

Lesson 17 — Splitting NumPy Arrays
----------------------------------
let's learn the opposite: splitting one array into multiple arrays.
<---np.split()--->
<---np.vsplit()--->
<---np.hsplit()--->

1️⃣ np.split()
-------------

In [17]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
result=np.split(arr,3)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


2️⃣ np.vsplit() — split vertically
---------------------------------

In [24]:
arr=np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
vertical_split=np.vsplit(arr,2)
print("Spliting array vertically:")
print(vertical_split)

Spliting array vertically:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


3️⃣ np.hsplit() — split horizontally
-----------------------------------

In [23]:
horizontal_split=np.split(arr,2)
print("spliting array horizontally:")
print(horizontal_split)

spliting array horizontally:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


🧠 Remember
------------


📝 Your Practice
----------------

In [31]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])
print("Use np.vsplit() to divide it into 2 equal parts.:")
vertical_split=np.vsplit(arr,2)
print(vertical_split)
print("Use np.hsplit() to divide it into 2 equal parts.:")
horizontal_split=np.hsplit(arr,2)
print(horizontal_split)
print("Shape of first vertical array:", vertical_split[0].shape)
print("Shape of second vertical array:", vertical_split[1].shape)
print("Shape of first horizontal array:", horizontal_split[0].shape)
print("Shape of second horizontal array:", horizontal_split[1].shape)

Use np.vsplit() to divide it into 2 equal parts.:
[array([[10, 20, 30, 40],
       [50, 60, 70, 80]]), array([[ 90, 100, 110, 120],
       [130, 140, 150, 160]])]
Use np.hsplit() to divide it into 2 equal parts.:
[array([[ 10,  20],
       [ 50,  60],
       [ 90, 100],
       [130, 140]]), array([[ 30,  40],
       [ 70,  80],
       [110, 120],
       [150, 160]])]
Shape of first vertical array: (2, 4)
Shape of second vertical array: (2, 4)
Shape of first horizontal array: (4, 2)
Shape of second horizontal array: (4, 2)


📘 Lesson 18 — Sorting & Searching in NumPy
---------------------------------------------
To sort data and find elements efficiently

1️⃣ np.sort()
---------------------------------
Sorts an array in ascending order.

In [33]:
import numpy as np
arr=np.array([50,20,80,10,40])
result=np.sort(arr)
print("Print the array in ascending order:",result)

Print the array in ascending order: [10 20 40 50 80]


2️⃣ Sorting a 2D array
----------------------
/----axis=1 → sort each row-----/
axis=0 → sort each column

In [38]:
arr = np.array([
    [30, 10, 20],
    [60, 40, 50]
])
print("sort each row:",np.sort(arr, axis=1))
print("sort each row:",np.sort(arr, axis=0))

sort each row: [[10 20 30]
 [40 50 60]]
sort each row: [[30 10 20]
 [60 40 50]]


3️⃣ np.argsort()
---------------
argsort():gives you the indices that would sort the array.

In [40]:
arr=np.array([50,20,80,10])
print(np.argsort(arr))

[3 1 0 2]


4️⃣ Searching with np.where()
----------------------------
np.where() can find the indices where a condition is true.

In [43]:
marks=np.array([45,67,82,91,55])
print(np.where(marks>70))
print(np.where(marks >= 70, "Pass", "Fail"))

(array([2, 3], dtype=int64),)
['Fail' 'Fail' 'Pass' 'Pass' 'Fail']


5️⃣ np.argmax() and np.argmin()
-------------------------------
These return the index of the maximum/minimum value.

In [45]:
arr = np.array([10, 50, 20, 80, 30])
print(np.argmax(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.min(arr))

3
0
80
10


🧠 Remember
------------

📝 Practice
-------------

In [53]:
arr = np.array([45, 12, 89, 34, 67, 23])
print("Sort the array using np.sort():")
print(np.sort(arr))
print("Find the index of the maximum value using np.argmax():")
print(np.argmax(arr))
print("Find the index of the minimum value using np.argmin():")
print(np.argmin(arr))
print("Use np.argsort() and predict its output:")
print(np.argsort(arr))
print("Use np.where() to find the indices where:")
print(np.where(arr>40))
marks = np.array([45, 78, 92, 55, 88, 61])
print("Indices of students whose marks are greater than or equal to 60:")
indices = np.where(marks >= 60)[0]
print(indices)

Sort the array using np.sort():
[12 23 34 45 67 89]
Find the index of the maximum value using np.argmax():
2
Find the index of the minimum value using np.argmin():
1
Use np.argsort() and predict its output:
[1 5 3 0 4 2]
Use np.where() to find the indices where:
(array([0, 2, 4], dtype=int64),)
Indices of students whose marks are greater than or equal to 60:
[1 2 4 5]


📘 Lesson 19 — Missing Values & NaN in NumPy
--------------------------------------------
In real datasets, some values may be missing. NumPy commonly represents missing numeric values using NaN — Not a Number.

1️⃣ Creating NaN


In [54]:
import numpy as np
arr = np.array([10, 20, np.nan, 40, 50])
print(arr)

[10. 20. nan 40. 50.]


2️⃣ Checking for NaN

In [55]:
np.isnan(arr)

array([False, False,  True, False, False])

3️⃣ np.nan can affect calculations

In [61]:
print(np.mean(arr))
print("Because the normal mean() encounters the NaN")
print(np.nanmean(arr))
print("It calculates the mean ignoring NaN.")

nan
Because the normal mean() encounters the NaN
30.0
It calculates the mean ignoring NaN.


4️⃣ Replacing NaN

In [62]:
arr[np.isnan(arr)] = 0
print(arr)

[10. 20.  0. 40. 50.]


In [63]:
arr = np.array([10., 20., np.nan, 40., 50.])
mean_value = np.nanmean(arr)
arr[np.isnan(arr)] = mean_value
print(arr)

[10. 20. 30. 40. 50.]


📝 Practice
------------

In [81]:
arr = np.array([10., 25., np.nan, 40., np.nan, 60.])
print("Find which elements are NaN using np.isnan():")
print(np.isnan(arr))
print("Extract only the NaN values:")
print(arr[np.isnan(arr)])
print("Calculate the mean using normal np.mean():")
print(np.mean(arr))
mean=np.nanmean(arr)
print("Calculate the mean while ignoring NaN",mean)
arr[np.isnan(arr)]=0
print("Replace all NaN values with 0:",arr)

Find which elements are NaN using np.isnan():
[False False  True False  True False]
Extract only the NaN values:
[nan nan]
Calculate the mean using normal np.mean():
nan
Calculate the mean while ignoring NaN 33.75
Replace all NaN values with 0: [10. 25.  0. 40.  0. 60.]
Replace every NaN with the mean of the non-missing values:


In [83]:
arr = np.array([10., 25., np.nan, 40., np.nan, 60.])
print("Replace every NaN with the mean of the non-missing values:")
mean_value = np.nanmean(arr)
arr[np.isnan(arr)] = mean_value
print(arr)

Replace every NaN with the mean of the non-missing values:
[10.   25.   33.75 40.   33.75 60.  ]


📘 Lesson 20 — NumPy Linear Algebra
-----------------------------------

In [89]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 4]
])
print("A:",A)
B = np.array([
    [5, 6],
    [7, 8]
])
print("B:",B)
print("Addition Of Two Matrix:")
print(A + B)
print("Subration Of Two Matrix:")
print(B-A)

A: [[1 2]
 [3 4]]
B: [[5 6]
 [7 8]]
Addition Of Two Matrix:
[[ 6  8]
 [10 12]]
Subration Of Two Matrix:
[[4 4]
 [4 4]]


Matrix multiplication ⭐
-----------------------
This is very important for ML.


🧠 Remember

In [94]:
print("performs element-wise multiplication:")
print(A * B)
print("Actual matrix multiplication:")
print(A @ B)
print("OR")
print(np.matmul(A, B))

performs element-wise multiplication:
[[ 5 12]
 [21 32]]
Actual matrix multiplication:
[[19 22]
 [43 50]]
OR
[[19 22]
 [43 50]]


Dot product
----------
for vectors

In [95]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))

32


Determinant
------------

In [96]:
A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.det(A))

-2.0000000000000004


Inverse of a matrix
-------------------

In [97]:
inverse = np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


📝 Practice

In [109]:
A = np.array([
    [2, 3],
    [4, 5]
])
B = np.array([
    [1, 2],
    [3, 4]
])
print("Calculate:(A+B)")
print(A+B)
print("Calculate:(A-B)")
print(A-B)
print("Calculate:(A*B)")
print(A*B)
print("Calculate:(A @ B)")
print(A@B)
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])
print("Calculate(np.linalg.det(A))")
print(np.linalg.det(A))
print("calculate(np.linalg.inv(A))")
print(np.linalg.inv(A))

Calculate:(A+B)
[[3 5]
 [7 9]]
Calculate:(A-B)
[[1 1]
 [1 1]]
Calculate:(A*B)
[[ 2  6]
 [12 20]]
Calculate:(A @ B)
[[11 16]
 [19 28]]
Calculate(np.linalg.det(A))
-2.0
calculate(np.linalg.inv(A))
[[-2.5  1.5]
 [ 2.  -1. ]]


📘 Lesson 21 — Statistics in NumPy 📊
-------------------------------------

1️⃣ Mean — Average

mean=(60 + 70 + 80 + 90 + 100) / 5 = 80

In [110]:
import numpy as np
marks = np.array([60, 70, 80, 90, 100])
print(np.mean(marks))

80.0


2️⃣ Median

The median is the middle value after sorting.

After sorting:

[10, 20, 30, 40, 50]

        ↑
          
       median
       
Why median is useful?

Median is less affected by extreme values (outliers) than the mean.

Example:[10, 20, 30, 40, 1000]

The mean becomes very large, but the median remains:

30

In [111]:
arr = np.array([10, 50, 20, 40, 30])
print(np.median(arr))

30.0


3️⃣ Minimum and Maximum

In [113]:
arr = np.array([10, 50, 20, 40, 30])
print(np.min(arr))
print(np.max(arr))

10
50


4️⃣ Standard Deviation — std()

Standard deviation tells us how spread out the data is around the mean

In [115]:
arr = np.array([10, 20, 30, 40, 50])
print(np.std(arr))

14.142135623730951


5️⃣ Variance — var()

Variance is related to standard deviation:

variance = (standard deviation)²

In [116]:
print(np.var(arr))

200.0


6️⃣ Percentile

A percentile tells us the value below which a certain percentage of observations fall.
    
np.percentile()

In [119]:
marks = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(np.percentile(marks, 50))
print(np.percentile(marks, 25))
print(np.percentile(marks, 75))

55.0
32.5
77.5


7️⃣ Statistics with axis

axis=0-------->column

axis=1-------->row

In [123]:
marks = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [90, 95, 85]
])
print("SUBJECTWISE MEAN:")
print(np.mean(marks,axis=0))
print("STUDENTWISE MEAN:")
print(np.mean(marks,axis=1))

SUBJECTWISE MEAN:
[76.66666667 83.33333333 83.33333333]
STUDENTWISE MEAN:
[80.         73.33333333 90.        ]


📝 Practice
------------

In [11]:
import numpy as np
arr = np.array([10,20, 30, 40, 50, 60, 70])
print("Find the mean:",np.mean(arr))
print("Find the median:",np.median(arr))
print("Find the minimum ",np.min(arr))
print("Find the maxmium ",np.max(arr))
print("Find the standard deviation:",np.std(arr))
print("Find the variance.",np.var(arr))
print("Find the 25th percentile",np.percentile(arr,25))
print("Find the 75th percentile:",np.percentile(arr,75))

Find the mean: 40.0
Find the median: 40.0
Find the minimum  10
Find the maxmium  70
Find the standard deviation: 20.0
Find the variance. 400.0
Find the 25th percentile 25.0
Find the 75th percentile: 55.0


In [13]:
marks = np.array([
    [60, 70, 80],
    [75, 85, 95],
    [90, 80, 70]
])
print("subjectwise mean:",np.mean(marks,axis=0))
print("studentwise mean:",np.mean(marks,axis=1))
print("Subjectwise standard deviation:",np.std(marks,axis=0))
print("studentwise maximum marks:",np.max(marks,axis=1))

subjectwise mean: [75.         78.33333333 81.66666667]
studentwise mean: [70. 85. 80.]
Subjectwise standard deviation: [12.24744871  6.23609564 10.27402334]
studentwise maximum marks: [80 95 90]


📘 Lesson 22 — Advanced NumPy
-------------------------------

1. What is vectorization?
--------------------------
Vectorization means performing an operation on an entire NumPy array at once, instead of manually looping through every element.

without Numpy
------------

In [15]:
marks=[50,60,70,80,95]
result=[]
for mark in marks:
    result.append(mark+5)
print(result)

[55, 65, 75, 85, 100]


with NumPy
-----------

In [16]:
import numpy as np
marks =np.array([50,60,70,80,90])
result=marks+5
print(result)

[55 65 75 85 95]


Example:students marks


In [17]:
marks=np.array([45,67,82,91,55])
percentage=marks/100*100
print(percentage)

[45. 67. 82. 91. 55.]


4. Vectorized conditions
---------------------------
You can also combine vectorization with Boolean indexing:

In [19]:
marks=np.array([45,67,82,91,55])
marks[marks>=60]+5

array([72, 87, 96])

🎯 Your Practice
----------------

In [29]:
import numpy as np
salary =np.array([25000, 30000, 35000, 40000, 50000])
increased=salary+5000
print("Add Rs 5000 to every salary:",increased)
multipy=salary*2
print("Multiply every salary by 2",multipy)
print("Find salaries greater than ₹35,000:")
print(salary[salary > 35000])
sal=salary[salary>35000]
bonus=sal+3000
print("Give a ₹3,000 bonus only to employees earning more than ₹35,000:",bonus)
salary_increase=salary+salary/10
print("Give every employee a 10% salary increase using a single NumPy expression.:",salary_increase)

Add Rs 5000 to every salary: [30000 35000 40000 45000 55000]
Multiply every salary by 2 [ 50000  60000  70000  80000 100000]
Find salaries greater than ₹35,000:
[40000 50000]
Give a ₹3,000 bonus only to employees earning more than ₹35,000: [43000 53000]
Give every employee a 10% salary increase using a single NumPy expression.: [27500. 33000. 38500. 44000. 55000.]


Lesson 22 — Topic 2: Universal Functions (ufuncs)
----------------------------------------------------
NumPy provides built-in mathematical functions that operate element-by-element on an entire array.

These are called Universal Functions (ufuncs).


🎯 Practice
------------

In [32]:
arr=np.array([1,4,9,16,25])
print("Find the square root of every value:",np.sqrt(arr))
print("Find the square of every value using np.square():",np.square(arr))
ar = np.array([-10, -5, 0, 5, 10])
print("Find the absolute value of every element:",np.abs(ar))
print("Calculate the exponential of every element using np.exp():",np.exp(ar))
arrr = np.array([1, 10, 100, 1000])
print("Calculate the natural logarithm of every element using np.log():",np.log(arrr))

Find the square root of every value: [1. 2. 3. 4. 5.]
Find the square of every value using np.square(): [  1  16  81 256 625]
Find the absolute value of every element: [10  5  0  5 10]
Calculate the exponential of every element using np.exp(): [4.53999298e-05 6.73794700e-03 1.00000000e+00 1.48413159e+02
 2.20264658e+04]
Calculate the natural logarithm of every element using np.log(): [0.         2.30258509 4.60517019 6.90775528]


Topic 3: Memory Efficiency — view() vs copy()

A view creates a new array object that shares the same underlying data, while a copy creates an independent array with its own data.

| Method   | Shares memory? | Changing it affects original? |
| -------- | -------------- | ----------------------------- |
| `view()` | ✅ Yes          | ✅ Usually yes                 |
| `copy()` | ❌ No           | ❌ No                          |


In [34]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
view_arr = arr.view()
view_arr[0]=999
print("view_arr:",view_arr)
print("arr",arr)

view_arr: [999  20  30  40  50]
arr [999  20  30  40  50]


In [36]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
copy_arr = arr.copy()
copy_arr[0]=999
print(copy_arr)
print(arr)

[999  20  30  40  50]
[10 20 30 40 50]


3. np.shares_memory()

NumPy provides:
np.shares_memory(array1, array2)

It returns:

True → both arrays share the same memory
False → they don't share memory

In [38]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

view_arr = arr.view()
copy_arr = arr.copy()

print(np.shares_memory(arr, view_arr))
print(np.shares_memory(arr, copy_arr))

True
False


What is Broadcasting?

Broadcasting allows NumPy to perform operations between arrays of different shapes.
When NumPy compares shapes, it works from the rightmost dimension.

🧠 Simple rule

Two dimensions are compatible if:

They are equal, or
One of them is 1, or
One dimension doesn't exist because the smaller array has fewer dimensions.

Topic 5: Memory & Array Efficiency

1. itemsize — memory used by one element

2. nbytes — total memory used by array data

   There are 4 elements × 8 bytes:
    4 × 8 = 32 bytes
   

🧠 Important interview point

itemsize tells us the memory occupied by one array element, while nbytes tells us the total memory occupied by the array's elements.

In [39]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50], dtype=np.int32)

print("dtype:", arr.dtype)
print("itemsize:", arr.itemsize)
print("nbytes:", arr.nbytes)
print("size:", arr.size)

dtype: int32
itemsize: 4
nbytes: 20
size: 5


In [40]:
arr64 = np.array([1, 2, 3, 4, 5], dtype=np.int64)
arr32 = np.array([1, 2, 3, 4, 5], dtype=np.int32)

print(arr64.itemsize)
print(arr64.nbytes)

print(arr32.itemsize)
print(arr32.nbytes)

8
40
4
20


In [50]:
import numpy as np

marks = np.array([
    [45, 78, 92],
    [66, 55, 88],
    [91, 73, 60],
    [82, 95, 49]
])
print("Select students 1 and 3.:",marks[[1,3]])
print(". Select only the second subject for all students:",marks[:,[1]])
print("Select students 0 and 3, and subjects 1 and 2:",marks[[0,3],[1,2]])
print("Select all marks greater than 80:",marks[marks>80])
marks[(marks>=60)& (marks<=90)]=0
print(marks)

Select students 1 and 3.: [[66 55 88]
 [82 95 49]]
. Select only the second subject for all students: [[78]
 [55]
 [73]
 [95]]
Select students 0 and 3, and subjects 1 and 2: [78 49]
Select all marks greater than 80: [92 88 91 82 95]
[[45  0 92]
 [ 0 55  0]
 [91  0  0]
 [ 0 95 49]]


Topic 7 — np.where() & Conditional Transformations

np.where() is very useful in data preprocessing, especially when you want to change values based on a condition.

np.where(condition, value_if_true, value_if_false)

In [58]:
marks = np.array([45, 67, 82, 91, 55, 73])
print("Find the indices where marks are greater than 80 using np.where():",np.where(marks>80)[0])
#print("Replace marks below 50 with 0 using np.where():",np.where(marks<50,0,marks))
print(np.where(marks>=50,"pass","fail"))
bonus=np.where(marks<60,10,0)
final_marks=marks+bonus
print(final_marks)


Find the indices where marks are greater than 80 using np.where(): [2 3]
['fail' 'pass' 'pass' 'pass' 'pass' 'pass']
[55 67 82 91 65 73]


Increase: [5000. 6000. 7000.    0.    0.]
Final salary: [30000. 36000. 42000. 40000. 50000.]


Topic 8 — np.einsum() & Advanced Numerical Operations

1. What is np.einsum()?

einsum stands for Einstein summation notation.

It lets us perform operations such as:

Sum ,
Dot product ,
Matrix multiplication ,
Transpose ,
Element-wise multiplication + summation .

In [63]:
import numpy as np
a = np.array([2, 4, 6])
b = np.array([3, 5, 7])

result = np.einsum('i,i->', a, b)

print(result)

68


In [61]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
np.einsum('ik,kj->ij', A, B)

array([[19, 22],
       [43, 50]])

🧠 einsum() patterns to remember
----------------------------------
| Operation             | `einsum()`    |
| --------------------- | ------------- |
| Dot product           | `'i,i->'`     |
| Matrix multiplication | `'ik,kj->ij'` |


In [73]:
numbers = np.array([10, 20, 30, 40, 50])
print("Multiply every value by 1.5 without using a loop:",numbers*1.5)
marks = np.array([35, 67, 42, 89, 55, 30])
marks[marks<50]=0
print("Replace every mark below 50 with 0, without a loop:",marks)

Multiply every value by 1.5 without using a loop: [15. 30. 45. 60. 75.]
Replace every mark below 50 with 0, without a loop: [ 0 67  0 89 55  0]


In [74]:
salary = np.array([25000, 45000, 32000, 60000, 28000])
bonus=np.where(salary<40000,salary*0.1,0)
final_salary=salary+bonus
print(final_salary)

[27500. 45000. 35200. 60000. 30800.]


In [120]:
import numpy as np
#Student_ID | Python | SQL | NumPy
students = np.array([
    [101, 78, 85, 92],
    [102, 45, 67, 55],
    [103, 88, 91, 84],
    [104, 32, 49, 40],
    [105, 72, 65, 78],
    [106, 95, 89, 93]
])
print(students.shape)
print(students.size)
print(students.ndim)
print(students[:,[1]])
print(students[:,[2]])
#print(np.mean(students[:,1]))
#print(np.mean(students[:,2]))
#print(np.mean(students[:,3]))
print(np.mean(students[:, 1:], axis=0))
student_averages=np.mean(students[:,1:],axis=1)
print("student_averages=",student_averages)
index = np.argmax(student_averages)
student_id = students[index, 0]
print(index)
print(student_id)
students[student_averages < 60, 0]
result=np.where(student_averages>=50,"pass","fail")
print(result)
subject_marks=students[:,1:]
bonus=np.where(subject_marks<50,5,0)
final_marks=subject_marks+bonus
print(final_marks)
print(np.max(students[:,1]))
print(np.min(students[:,2]))
print(np.mean(students[:,3]))
count=np.where(student_averages>=70,1,0)
print(np.sum(count))
highest_index=np.argmax(student_averages)
highest_student_id=students[highest_index,0]
print(highest_student_id)

(6, 4)
24
2
[[78]
 [45]
 [88]
 [32]
 [72]
 [95]]
[[85]
 [67]
 [91]
 [49]
 [65]
 [89]]
[68.33333333 74.33333333 73.66666667]
student_averages= [85.         55.66666667 87.66666667 40.33333333 71.66666667 92.33333333]
5
106
['pass' 'pass' 'pass' 'fail' 'pass' 'pass']
[[78 85 92]
 [50 67 55]
 [88 91 84]
 [37 54 45]
 [72 65 78]
 [95 89 93]]
95
49
73.66666666666667
4
106


In [121]:
import numpy as np

students = np.array([
    [101, 78, 85, 92],
    [102, 45, 67, 55],
    [103, 88, 91, 84],
    [104, 32, 49, 40],
    [105, 72, 65, 78],
    [106, 95, 89, 93]
])

# 1. Calculate overall average for each student
student_averages = np.mean(students[:, 1:], axis=1)

print("Averages:", student_averages)

# 2. Classify students
result = np.where(
    student_averages >= 85,
    "Excellent",
    np.where(
        student_averages >= 70,
        "Good",
        np.where(
            student_averages >= 50,
            "Average",
            "Fail"
        )
    )
)

print("Result:", result)

Averages: [85.         55.66666667 87.66666667 40.33333333 71.66666667 92.33333333]
Result: ['Excellent' 'Average' 'Excellent' 'Fail' 'Good' 'Excellent']
