# 💼 Salary Analysis using NumPy
This project analyzes employee salary, experience, and performance data using NumPy.

The goal is to apply NumPy concepts to a practical, internship-oriented dataset.


## 🎯 Objectives

- Analyze employee salaries
- Analyze employee experience
- Analyze employee performance
- Use NumPy statistical functions
- Practice Boolean indexing and `np.where()`
- Apply conditional salary increases
- Identify employees based on multiple conditions

In [1]:
import numpy as np 
#Employee_ID | Salary | Experience | Performance
employees=np.array([
    [101,25000,2,65],
    [102,45000,5,82],
    [103,32000,3,70],
    [104,60000,8,95],
    [105,28000,1,55],
    [106,52000,6,88]
])
print(employees)

[[  101 25000     2    65]
 [  102 45000     5    82]
 [  103 32000     3    70]
 [  104 60000     8    95]
 [  105 28000     1    55]
 [  106 52000     6    88]]


In [4]:
print("Shape",employees.shape)
print("Size",employees.size)
print("ndim:",employees.ndim)

Shape (6, 4)
Size 24
ndim: 2


In [13]:
print("Employees IDs:",employees[:,0])
print("Salaries:",employees[:,1])
print("Experience:",employees[:,2])
print("Performance:",employees[:,3])

Employees IDs: [101 102 103 104 105 106]
Salaries: [25000 45000 32000 60000 28000 52000]
Experience: [2 5 3 8 1 6]
Performance: [65 82 70 95 55 88]


## 💰 Salary Analysis

Let's calculate the average, maximum, minimum, and standard deviation of employee salaries.

In [28]:
print("Average Salary:",np.mean(employees[:,1],axis=0))
print("Maximum Salary:",np.max(employees[:,1],axis=0))
print("Minimum Salary:",np.min(employees[:,1],axis=0))
print("Standard Deviation Of Salary:",np.std(employees[:,1],axis=0))

Average Salary: 40333.333333333336
Maximum Salary: 60000
Minimum Salary: 25000
Standard Deviation Of Salary: 12918.548250050735


In [48]:
high_performance_index=np.where(employees[:,3]>80)[0]
high_performance_ids=employees[high_performance_index,0]
print("High Performance Employee IDs:", high_performance_ids)

High Performance Employee IDs: [102 104 106]


In [92]:
salaries = employees[:, 1]
print("salaries:",salaries )
salary_increase=np.where(salaries<40000,salaries*0.1,0)
final_salary=salaries+salary_increase
print("salary_increase:",salary_increase)
print("final_salary:",final_salary)

salaries: [25000 45000 32000 60000 28000 52000]
salary_increase: [2500.    0. 3200.    0. 2800.    0.]
final_salary: [27500. 45000. 35200. 60000. 30800. 52000.]


In [57]:
avg_performance=np.mean(employees[:,3])
print(avg_performance)
high_performance_index=np.where(employees[:,3]>=80)[0]
high_performance=employees[high_performance_index,0]
print("High Performance Employee IDs:", high_performance)


75.83333333333333
High Performance Employee IDs: [102 104 106]


In [58]:
performance = employees[:, 3]

highest_performance_index = np.argmax(performance)

highest_performance_id = employees[highest_performance_index, 0]

print("Highest Performance:", performance[highest_performance_index])
print("Employee ID:", highest_performance_id)

Highest Performance: 95
Employee ID: 104


## 📈 Experience Analysis

Let's analyze employee experience and identify the most experienced employees.

In [91]:
experience=employees[:,2]
print("experience:",experience)
avg_experience=np.mean(experience)
print("avg_experience:",avg_experience)
highest_experience_index=np.argmax(experience)
highest_experience_id=employees[highest_experience_index,0]
print("Highest Experience:", experience[highest_experience_index])
print("Employee ID:", highest_experience_id)
high_experience_index = np.where(experience > 4)[0]
high_experience_id=employees[high_experience_index ,0]
print("Employee IDs having more than 4 years of experience.:",high_experience_id)

experience: [2 5 3 8 1 6]
avg_experience: 4.166666666666667
Highest Experience: 8
Employee ID: 104
Employee IDs having more than 4 years of experience.: [102 104 106]


In [66]:
performance_category=np.where(performance>=90,"Excellent",np.where(performance>=80,"GOOD",np.where(performance>=60,"AVERAGE","POOR")))
print("RESULT:",performance_category)

RESULT: ['AVERAGE' 'GOOD' 'AVERAGE' 'Excellent' 'POOR' 'GOOD']


In [83]:
salaries=employees[:,1]
print(salaries)
highest_salary=np.max(salaries)
print("Highest salary:",highest_salary)
highest_paid_index=np.argmax(salaries)
print("Employee ID of the highest-paid employee:",employees[highest_paid_index,0])
lowest_salary=np.min(salaries)
print("Lowest salary:",lowest_salary)
lowest_paid_index=np.argmin(salaries)
print("Employee ID of the lowest-paid employee:",employees[lowest_paid_index,0])
count40=np.sum(salaries > 40000)
print(count40)

[25000 45000 32000 60000 28000 52000]
Highest salary: 60000
Employee ID of the highest-paid employee: 104
Lowest salary: 25000
Employee ID of the lowest-paid employee: 101
3


In [89]:
index = np.where((salaries > 40000) & (performance > 80))[0]
employee_ids = employees[index, 0]
print("Employee IDs:", employee_ids)

Employee IDs: [102 104 106]
